export const INCREMENT_VOTE = 'INCREMENT_VOTE';
export const DECREMENT_VOTE = 'DECREMENT_VOTE';
export const FETCH_CAT_LIST = 'FETCH_CAT_LIST';
export const FETCH_CAT_LIST_ERROR = 'FETCH_CAT_LIST_ERROR';
export const FETCH_TWO_CAT_LIST = 'FETCH_TWO_CAT_LIST';
export const FETCH_OTHER_CAT_LIST = 'FETCH_OTHER_CAT_LIST';